RFC 3442 - Classless Static Route Option for DHCPv4 (#516325)

diff --git a/dhclient-script b/dhclient-script
--- a/dhclient-script
+++ b/dhclient-script
@@ -171,13 +171,28 @@ num2ip() {
     echo "${o1}.${o2}.${o3}.${o4}"
 }
 
-mask() {
+get_network_address() {
+# get network address for the given IP address and (netmask or prefix)
     ip="${1}"
-    m="${2}"
-    let ip="$(IFS="." ip2num ${ip})"
-    let m="$(IFS="." ip2num ${m})"
-    let n="ip & m"
-    num2ip ${n}
+    nm="${2}"
+
+    if [ -n "${ip}" -a -n "${nm}" ]; then
+        if [[ "${nm}" = *.* ]]; then
+            ipcalc -s -n ${ip} ${nm} | cut -d '=' -f 2
+        else
+            ipcalc -s -n ${ip}/${nm} | cut -d '=' -f 2
+        fi
+    fi
+}
+
+get_prefix() {
+# get prefix for the given IP address and mask
+    ip="${1}"
+    nm="${2}"
+
+    if [ -n "${ip}" -a -n "${nm}" ]; then
+        ipcalc -s -p ${ip} ${nm} | cut -d '=' -f 2
+    fi
 }
 
 class_bits() {
@@ -198,8 +213,8 @@ class_bits() {
 is_router_reachable() {
     # handle DHCP servers that give us a router not on our subnet
     router="${1}"
-    routersubnet="$(mask ${router} ${new_subnet_mask})"
-    mysubnet="$(mask ${new_ip_address} ${new_subnet_mask})"
+    routersubnet="$(get_network_address ${router} ${new_subnet_mask})"
+    mysubnet="$(get_network_address ${new_ip_address} ${new_subnet_mask})"
     unreachable=0
 
     if [ ! "${routersubnet}" = "${mysubnet}" ]; then
@@ -280,6 +295,69 @@ dhconfig() {
             . ${ETCDIR}/dhclient-up-hooks
         fi
 
+        # static routes
+        if [ -n "${new_classless_static_routes}" ] ||
+           [ -n "${new_static_routes}" ]; then
+            if [ -n "${new_classless_static_routes}" ]; then
+                IFS=', |' static_routes=(${new_classless_static_routes})
+
+                # If the DHCP server returns both a Classless Static Routes option and
+                # a Router option, the DHCP client MUST ignore the Router option. (RFC3442)
+                new_routers=""
+            else
+                IFS=', |' static_routes=(${new_static_routes})
+            fi
+            route_targets=()
+
+            for((i=0; i<${#static_routes[@]}; i+=2)); do
+                target=${static_routes[$i]}
+                if [ -n "${new_classless_static_routes}" ]; then
+                    prefix=$(echo ${target} | cut -d "." -f 1)
+                    target=$(echo ${target} | cut -d "." -f 2-)
+                    IFS="." target_arr=(${target})
+                    unset IFS
+                    ((pads=4-${#target_arr[@]}))
+                    for j in $(seq $pads); do
+                        target=${target}".0"
+                    done
+
+                    # Client MUST zero any bits in the subnet number where the corresponding bit in the mask is zero.
+                    # In other words, the subnet number installed in the routing table is the logical AND of
+                    # the subnet number and subnet mask given in the Classless Static Routes option. (RFC3442)
+                    target="$(get_network_address ${target} ${prefix})"
+                else
+                    prefix=$(class_bits ${target})
+                fi
+                gateway=${static_routes[$i+1]}
+
+                metric=''
+                for t in ${route_targets[@]}; do
+                    if [ ${t} = ${target} ]; then
+                        if [ -z "${metric}" ]; then
+                            metric=1
+                        else
+                            ((metric=metric+1))
+                        fi
+                    fi
+                done
+
+                if [ -n "${metric}" ]; then
+                    metric="metric ${metric}"
+                fi
+
+                if is_router_reachable ${gateway}; then
+                    ip -4 route replace ${target}/${prefix} via ${gateway} dev ${interface} ${metric}
+
+                    if [ $? -ne 0 ]; then
+                        logmessage "failed to create static route: ${target}/${prefix} via ${gateway} dev ${interface} ${metric}"
+                    else
+                        route_targets=(${route_targets[@]} ${target})
+                    fi
+                fi
+            done
+        fi
+
+        # gateways
         if [[ ( "${DEFROUTE}" != "no") &&
               (( -z "${GATEWAYDEV}" ) ||
                ( "${GATEWAYDEV}" = "${interface}" )) ]]; then
@@ -313,8 +391,8 @@ dhconfig() {
                     metric=${i}
                 done
             elif [ -n "${GATEWAY}" ]; then
-                routersubnet=$(mask ${GATEWAY} ${new_subnet_mask})
-                mysubnet=$(mask ${new_ip_address} ${new_subnet_mask})
+                routersubnet=$(get_network_address ${GATEWAY} ${new_subnet_mask})
+                mysubnet=$(get_network_address ${new_ip_address} ${new_subnet_mask})
 
                 if [ "${routersubnet}" = "${mysubnet}" ]; then
                     ip -4 route replace default via ${GATEWAY} dev ${interface}
@@ -322,41 +400,6 @@ dhconfig() {
             fi
         fi
 
-        # static routes
-        if [ -n "${new_static_routes}" ]; then
-            IFS=', |' static_routes=(${new_static_routes})
-            route_targets=()
-
-            for((i=0; i<${#static_routes[@]}; i+=2)); do
-                target=${static_routes[$i]}
-                gateway=${static_routes[$i+1]}
-                metric=''
-
-                for t in ${route_targets[@]}; do
-                    if [ ${t} = ${target} ]; then
-                        if [ -z "${metric}" ]; then
-                            metric=1
-                        else
-                            ((metric=metric+1))
-                        fi
-                    fi
-                done
-
-                if [ -n "${metric}" ]; then
-                    metric="metric ${metric}"
-                fi
-
-                if is_router_reachable ${gateway}; then
-                    ip -4 route replace ${target}/$(class_bits ${target}) via ${gateway} dev ${interface} ${metric}
-
-                    if [ $? -ne 0 ]; then
-                        logmessage "failed to create static route: ${target}/$(class_bits ${target}) via ${gateway} dev ${interface} ${metric}"
-                    else
-                        route_targets=(${route_targets[@]} ${target})
-                    fi
-                fi
-            done
-        fi
     fi
 
     if [ ! "${new_ip_address}" = "${alias_ip_address}" ] &&
@@ -487,15 +530,6 @@ dh6config() {
                 "${subsystem}_config"
             fi
         done
-    fi
-}
-
-get_prefix() {
-    ip="${1}"
-    nm="${2}"
-
-    if [ -n "${ip}" -a -n "${nm}" ]; then
-        ipcalc -s -p ${ip} ${nm} | cut -d '=' -f 2
     fi
 }
 
