s/ping/arping/ in dhclient-script to handle not-on-local-net gateway in ARP-less device (#524298)

diff --git a/dhclient-script b/dhclient-script
--- a/dhclient-script
+++ b/dhclient-script
@@ -215,24 +215,24 @@ is_router_reachable() {
     router="${1}"
     routersubnet="$(get_network_address ${router} ${new_subnet_mask})"
     mysubnet="$(get_network_address ${new_ip_address} ${new_subnet_mask})"
-    unreachable=0
 
     if [ ! "${routersubnet}" = "${mysubnet}" ]; then
-        unreachable=1
-        if arping -f -q -I ${interface} -w2 ${router}; then
-            ip -4 route add ${router}/32 dev ${interface}
-            if [ $? -eq 0 ]; then
-                unreachable=0
+        ip -4 route add ${router}/32 dev ${interface}
+        if [ $? -eq 0 ]; then
+            if ping -q -c1 -w2 -I ${interface} ${router}; then
+                return 0
             else
-                logmessage "failed to create host router for unreachable router ${router} not on subnet ${mysubnet}"
+                logmessage "DHCP router ${router} is unreachable on DHCP subnet ${mysubnet} router subnet ${routersubnet}"
+                ip route del ${router}/32 dev ${interface}
+                return 1
             fi
         else
-            unreachable=1
-            logmessage "DHCP router ${router} is unreachable on DHCP subnet ${mysubnet} router subnet ${routersubnet}"
+            logmessage "failed to create host router for unreachable router ${router} not on subnet ${mysubnet}"
+            return 1
         fi
     fi
 
-    return ${unreachable}
+    return 0
 }
 
 add_default_gateway() {
